services:
  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: always

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "SenhaForte123!@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - backend
    volumes:
      - ./src/main/resources/products.sql:/docker-entrypoint-initdb.d/products.sql
      - sqlserver_data:/var/opt/mssql
    restart: always

  sqlserver-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    entrypoint: /bin/bash -c "sleep 20 && /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P 'SenhaForte123!@' -d master -i /docker-entrypoint-initdb.d/products.sql"
    volumes:
      - ./src/main/resources/products.sql:/docker-entrypoint-initdb.d/products.sql
    networks:
      - backend

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SenhaForte123!@
      POSTGRES_DB: hackdb
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

networks:
  backend:
    driver: bridge

volumes:
  sqlserver_data:
  postgres_data:
