-- V1__create_tables.sql
CREATE TABLE IF NOT EXISTS PRODUTO (
  CO_PRODUTO INT NOT NULL PRIMARY KEY,
  NO_PRODUTO VARCHAR(200) NOT NULL,
  PC_TAXA_JUROS DECIMAL(10,9) NOT NULL,
  NU_MINIMO_MESES SMALLINT NOT NULL,
  NU_MAXIMO_MESES SMALLINT NULL,
  VR_MINIMO DECIMAL(18,2) NOT NULL,
  VR_MAXIMO DECIMAL(18,2) NULL
);
-- Simulacao
CREATE TABLE IF NOT EXISTS SIMULACAO (
  ID_SIMULACAO BIGINT IDENTITY(1,1) PRIMARY KEY,
  CO_PRODUTO INT NOT NULL,
  VALOR_DESEJADO DECIMAL(18,2) NOT NULL,
  PRAZO INT NOT NULL,
  DATA_REFERENCIA DATE NOT NULL DEFAULT CAST(GETDATE() AS DATE),
  VALOR_TOTAL_PARCELAS DECIMAL(18,2) NOT NULL,
  CONSTRAINT FK_SIM_PROD FOREIGN KEY (CO_PRODUTO) REFERENCES PRODUTO(CO_PRODUTO)
);
CREATE INDEX IX_SIMULACAO_DATA_PROD ON SIMULACAO (DATA_REFERENCIA, CO_PRODUTO);
